In [1]:
import numpy as np
from tqdm import tqdm

In [2]:
# x = np.load("examples_new_460000.npy", allow_pickle=True)
x = np.load("grid_regression_1010000.npy", allow_pickle=True)

In [3]:
NUM_STATES = 1010000
states = np.zeros([NUM_STATES, 150, 25], dtype=int)
rewards = np.zeros([NUM_STATES, 150], dtype=float)
for idx, example in tqdm(enumerate(x)):
    data = example["data"]
    traj_states = np.zeros([150, 25], dtype=int)
    traj_rewards = np.zeros([150], dtype=float)
    for t in range(len(data)):
        traj_states[t] = data[t][0]
        traj_rewards[t] = data[t][1]
    states[idx] = traj_states
    rewards[idx] = traj_rewards

1010000it [02:05, 8041.66it/s]


In [4]:
states[0]

array([[2, 3, 3, ..., 3, 1, 0],
       [3, 3, 3, ..., 1, 0, 3],
       [3, 3, 0, ..., 3, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 1, 0, 3],
       [1, 3, 3, ..., 3, 1, 0]])

In [8]:
rewards[1]

array([ 3.11522652,  2.85854911, 15.83284649, 15.82101331, 15.07947697,
       13.59303336,  1.83364773, 13.92865464, 14.44652738,  9.73233309,
       14.46256275, 13.60938641, 13.47517707,  0.09787198,  0.53635127,
        0.09787198,  0.53635127,  1.25498453,  2.50037042, 15.72869366,
       15.48005089, 14.55800751,  1.95608383, 13.65084849,  8.85511872,
        0.57064193,  9.01197338,  1.32283054, 14.70248346, 13.95029485,
        8.66323807,  0.52248794,  1.06310389,  1.23425349, 13.63933106,
        0.26202597,  0.21387198,  0.46047062,  0.91250952, 13.68909757,
        1.15123534,  9.93647852,  2.40534329,  3.04605177, 15.14237149,
       13.84649971,  8.54080198,  0.62708636, 12.73959927,  0.26932529,
        1.12671974,  2.16462123, 10.08094049,  2.82296362, 14.62949813,
        9.71981249,  9.86366704, 14.37690898, 14.07781034,  1.48784775,
       14.30862942,  1.54911576,  2.45392888, 15.46103425, 14.65136218,
       14.55406308, 10.45462301,  2.22986421,  1.50084785,  2.37

In [4]:
states_copy = np.copy(states)

In [6]:
perm = np.arange(4)
np.random.shuffle(perm)
perm

array([1, 3, 0, 2])

In [7]:
states_copy[1]

array([[3, 3, 3, ..., 3, 3, 2],
       [1, 3, 3, ..., 3, 1, 3],
       [1, 1, 3, ..., 3, 3, 1],
       ...,
       [3, 3, 3, ..., 3, 3, 1],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [8]:
perm[states_copy[1]]

array([[2, 2, 2, ..., 2, 2, 0],
       [3, 2, 2, ..., 2, 3, 2],
       [3, 3, 2, ..., 2, 2, 3],
       ...,
       [2, 2, 2, ..., 2, 2, 3],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [5]:
# np.save("states_460000.npy", states)

In [6]:
# np.save("rewards_460000.npy", rewards)

In [10]:
np.save("states_100000.npy", states)
np.save("rewards_100000.npy", rewards)

In [5]:
np.save(f"states_{NUM_STATES}.npy", states)
np.save(f"rewards_{NUM_STATES}.npy", rewards)

In [7]:
np.save("states_4600.npy", states[:4600])

In [8]:
np.save("rewards_4600.npy", rewards[:4600])

In [9]:
np.save("states_46000.npy", states[:46000])

In [10]:
np.save("rewards_46000.npy", rewards[:46000])

In [4]:
np.save("states_60000.npy", states[:60000])

In [5]:
np.save("rewards_60000.npy", rewards[:60000])

In [12]:
states.shape

(460000, 150, 25)

In [15]:
states[:, :, 12]

array([[3, 3, 3, ..., 1, 3, 3],
       [3, 2, 1, ..., 3, 1, 3],
       [3, 1, 1, ..., 1, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 2, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])