In [3]:
import numpy as np
from tqdm import tqdm

In [1]:
NUM_STATES = 1010000

In [5]:
# x = np.load("examples_new_460000.npy", allow_pickle=True)
# x = np.load(f"data/grid_regression_with_weights_{NUM_STATES}.npy", allow_pickle=True)

In [5]:
states = np.zeros([NUM_STATES, 150, 25], dtype=int)
rewards = np.zeros([NUM_STATES, 150], dtype=float)
weights = np.zeros([NUM_STATES, 3], dtype=float)
for idx, example in tqdm(enumerate(x)):
    weights[idx] = example["weights"]
    data = example["data"]
    traj_states = np.zeros([150, 25], dtype=int)
    traj_rewards = np.zeros([150], dtype=float)
    for t in range(len(data)):
        traj_states[t] = data[t][0]
        traj_rewards[t] = data[t][1]
    states[idx] = traj_states
    rewards[idx] = traj_rewards

1010000it [02:05, 8047.23it/s]


In [13]:
states = np.load(f"data/states_{NUM_STATES}.npy")
rewards = np.load(f"data/rewards_{NUM_STATES}.npy")
weights = np.load(f"data/weights_{NUM_STATES}.npy")

In [4]:
shuffled_states = np.load(f"data/shuffled_states_{NUM_STATES}.npy")
shuffled_rewards = np.load(f"data/shuffled_rewards_{NUM_STATES}.npy")
shuffled_weights = np.load(f"data/shuffled_weights_{NUM_STATES}.npy")

In [5]:
shuffled_states_small = shuffled_states[:10100]
shuffled_rewards_small = shuffled_rewards[:10100]
shuffled_weights_small = shuffled_weights[:10100]

In [6]:
np.save(f"data/shuffled_states_10100.npy", shuffled_states_small)
np.save(f"data/shuffled_rewards_10100.npy", shuffled_rewards_small)
np.save(f"data/shuffled_weights_10100.npy", shuffled_weights_small)

In [89]:
summed = weights.sum(axis=1)
summed_sorted_indices = np.argsort(summed)
# sorted_summed = weights[summed_sorted_indices]
sorted_states = states[summed_sorted_indices]
sorted_rewards = rewards[summed_sorted_indices]
sorted_weights = weights[summed_sorted_indices]

In [88]:
weights[summed_sorted_indices]

array([[-0.58296714, -0.57661197, -0.57242288],
       [-0.58296714, -0.57661197, -0.57242288],
       [-0.58296714, -0.57661197, -0.57242288],
       ...,
       [ 0.57954381,  0.57684721,  0.5756529 ],
       [ 0.57954381,  0.57684721,  0.5756529 ],
       [ 0.57954381,  0.57684721,  0.5756529 ]])

In [79]:
sorted_states.shape

(1010000, 150, 25)

In [90]:
sorted_states_unflattened = np.reshape(sorted_states, (-1, 100, sorted_states.shape[-2], sorted_states.shape[-1]))
sorted_rewards_unflattened = np.reshape(sorted_rewards, (-1, 100, sorted_rewards.shape[-1]))
sorted_weights_unflattened = np.reshape(sorted_weights, (-1, 100, sorted_weights.shape[-1]))

In [91]:
print(sorted_states_unflattened.shape)
print(sorted_rewards_unflattened.shape)
print(sorted_weights_unflattened.shape)

(10100, 100, 150, 25)
(10100, 100, 150)
(10100, 100, 3)


In [92]:
shuffled_idxs = np.random.permutation(NUM_STATES//100)

In [93]:
shuffled_idxs

array([1564, 5066, 3625, ..., 1041, 3168, 2251])

In [94]:
shuffled_states_unflattened = sorted_states_unflattened[shuffled_idxs]
shuffled_rewards_unflattened = sorted_rewards_unflattened[shuffled_idxs]
shuffled_weights_unflattened = sorted_weights_unflattened[shuffled_idxs]

In [96]:
shuffled_states = np.reshape(shuffled_states_unflattened, (-1, shuffled_states_unflattened.shape[-2], shuffled_states_unflattened.shape[-1]))
shuffled_rewards = np.reshape(shuffled_rewards_unflattened, (-1, shuffled_rewards_unflattened.shape[-1]))
shuffled_weights = np.reshape(shuffled_weights_unflattened, (-1, shuffled_weights_unflattened.shape[-1]))

In [103]:
np.save(f"data/shuffled_states_{NUM_STATES}.npy", shuffled_states)
np.save(f"data/shuffled_rewards_{NUM_STATES}.npy", shuffled_rewards)
np.save(f"data/shuffled_weights_{NUM_STATES}.npy", shuffled_weights)

In [101]:
# np.unique(shuffled_weights, axis=0, return_inverse=True)[1][0:100]

array([521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521, 521,
       521, 521, 521, 521, 521, 521, 521, 521, 521])

In [60]:
sorted_weights_indices = np.argsort(weights, axis=0)
sorted_weights_indices

array([[948881, 995478, 555733],
       [100480, 268279, 818333],
       [888280, 248078, 676932],
       ...,
       [832576, 291400,  67636],
       [468976, 796400, 875636],
       [  4377, 271201, 613037]])

In [46]:
# 
np.unique(weights, axis=0, return_inverse=True)[1]

array([ 340,  340, 2260, ..., 3017, 4529, 4529])

In [35]:
all_weight_positions = np.zeros((NUM_STATES//100, 100), dtype=int)
for idx, weight_set in tqdm(enumerate(np.unique(weights))):
    all_weight_positions[idx] = np.nonzero(np.all((weights == weights[0]), axis=1))[0]
    
# first_weights = np.nonzero(np.all((weights == weights[0]), axis=1))
# first_weights
# states[first_weights].shape
# for weight in np.unique(weights, axis=0):
    

8057it [02:55, 45.86it/s]


KeyboardInterrupt: 

In [38]:
for i in tqdm(range(NUM_STATES)):
    

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1010000/1010000 [00:00<00:00, 2368415.28it/s]


In [6]:
states[0]

array([[2, 0, 3, ..., 3, 3, 3],
       [3, 0, 0, ..., 3, 3, 3],
       [2, 0, 3, ..., 3, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [23]:
rewards[5000]

array([10.18885403, 12.21433581,  3.15487071, 18.94940075,  3.19103176,
       18.11223085,  7.82594034,  1.78203997,  1.39175277, 10.11324955,
        0.71283505,  1.56211507,  7.76660506, 16.77078216,  0.68539243,
        7.06386532,  0.99316186,  1.9413464 , 17.84870964, 11.03568938,
        7.40704388,  1.77736511, 16.8160805 ,  1.41534585,  8.57632409,
       17.89465163, 17.29654965,  1.12928168,  1.12278827,  1.3619686 ,
       10.53958953,  2.25028661, 17.45309981,  1.22743015,  7.91057486,
        8.13050388,  1.4512821 ,  7.28642997,  7.84145863,  1.88668597,
       17.19425345,  1.55977764,  1.35559172,  1.40621269,  1.49159914,
        1.85285822,  2.15020718,  2.13575139, 11.20978881, 17.11746891,
        1.0897207 ,  1.13268161,  1.4619315 , 16.84054203,  0.97753116,
       10.08591934,  1.01709627,  1.91008913, 11.53382846, 18.29078858,
        8.02140783, 11.22201958, 17.13543704,  1.18458577,  0.80056305,
        7.12086731,  0.61393466,  1.38526349,  2.12510612, 12.12

In [22]:
weights[5000]

array([0.8167437 , 0.32796258, 0.4747318 ])

In [4]:
states_copy = np.copy(states)

In [6]:
perm = np.arange(4)
np.random.shuffle(perm)
perm

array([1, 3, 0, 2])

In [7]:
states_copy[1]

array([[3, 3, 3, ..., 3, 3, 2],
       [1, 3, 3, ..., 3, 1, 3],
       [1, 1, 3, ..., 3, 3, 1],
       ...,
       [3, 3, 3, ..., 3, 3, 1],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [8]:
perm[states_copy[1]]

array([[2, 2, 2, ..., 2, 2, 0],
       [3, 2, 2, ..., 2, 3, 2],
       [3, 3, 2, ..., 2, 2, 3],
       ...,
       [2, 2, 2, ..., 2, 2, 3],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [5]:
# np.save("states_460000.npy", states)

In [6]:
# np.save("rewards_460000.npy", rewards)

In [10]:
np.save("states_100000.npy", states)
np.save("rewards_100000.npy", rewards)

In [24]:
np.save(f"states_{NUM_STATES}.npy", states)
np.save(f"rewards_{NUM_STATES}.npy", rewards)
np.save(f"weights_{NUM_STATES}.npy", weights)

In [25]:
NUM_STATES_TEST = 10100

In [26]:
np.save(f"states_{NUM_STATES_TEST}.npy", states[:NUM_STATES_TEST])
np.save(f"rewards_{NUM_STATES_TEST}.npy", rewards[:NUM_STATES_TEST])
np.save(f"weights_{NUM_STATES_TEST}.npy", weights[:NUM_STATES_TEST])

In [7]:
np.save("states_4600.npy", states[:4600])

In [8]:
np.save("rewards_4600.npy", rewards[:4600])

In [9]:
np.save("states_46000.npy", states[:46000])

In [10]:
np.save("rewards_46000.npy", rewards[:46000])

In [4]:
np.save("states_60000.npy", states[:60000])

In [5]:
np.save("rewards_60000.npy", rewards[:60000])

In [12]:
states.shape

(460000, 150, 25)

In [15]:
states[:, :, 12]

array([[3, 3, 3, ..., 1, 3, 3],
       [3, 2, 1, ..., 3, 1, 3],
       [3, 1, 1, ..., 1, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 2, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])