In [1]:
import numpy as np
from tqdm import tqdm

In [2]:
x = np.load("examples_new_460000.npy", allow_pickle=True)

In [3]:
states = np.zeros([460000, 150, 25], dtype=int)
rewards = np.zeros([460000, 150], dtype=float)
for idx, example in tqdm(enumerate(x)):
    data = example["data"]
    traj_states = np.zeros([150, 25], dtype=int)
    traj_rewards = np.zeros([150], dtype=float)
    for t in range(len(data)):
        traj_states[t] = data[t][0]
        traj_rewards[t] = data[t][1]
    states[idx] = traj_states
    rewards[idx] = traj_rewards

460000it [00:54, 8438.65it/s]


In [4]:
x[10000]

{'block_types': [<BlockType.NEUTRAL: 2>,
  <BlockType.NEGATIVE: 0>,
  <BlockType.NEGATIVE: 0>],
 'block_powers': [0.0, 0.7427370001886512, 0.6695832648377374],
 'data': [(array([3, 3, 3, 0, 0, 3, 2, 3, 3, 0, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 0, 2,
          0, 3, 3]),
   -1.1453566865132),
  (array([3, 3, 3, 3, 0, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 0,
          2, 0, 3]),
   -0.6187846594345926),
  (array([2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3,
          0, 2, 0]),
   -0.5071874486283031),
  (array([3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 0, 3,
          3, 0, 2]),
   -0.3955902378220135),
  (array([3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2,
          3, 3, 3]),
   -0.005),
  (array([3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
          2, 3, 3]),
   -0.3397916324188687),
  (array([3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2,
          3, 3, 3]),
   -0.005),
  (arra

In [5]:
np.save("states_460000.npy", states)

In [6]:
np.save("rewards_460000.npy", rewards)

In [7]:
np.save("states_4600.npy", states[:4600])

In [8]:
np.save("rewards_4600.npy", rewards[:4600])

In [9]:
np.save("states_46000.npy", states[:46000])

In [10]:
np.save("rewards_46000.npy", rewards[:46000])

In [4]:
np.save("states_60000.npy", states[:60000])

In [5]:
np.save("rewards_60000.npy", rewards[:60000])

In [12]:
states.shape

(460000, 150, 25)

In [15]:
states[:, :, 12]

array([[3, 3, 3, ..., 1, 3, 3],
       [3, 2, 1, ..., 3, 1, 3],
       [3, 1, 1, ..., 1, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 2, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])