In [1]:
import numpy as np
from tqdm import tqdm

In [2]:
# x = np.load("examples_new_460000.npy", allow_pickle=True)
x = np.load("grid_regression_with_weights_1010000.npy", allow_pickle=True)

In [3]:
NUM_STATES = 1010000

In [5]:
states = np.zeros([NUM_STATES, 150, 25], dtype=int)
rewards = np.zeros([NUM_STATES, 150], dtype=float)
weights = np.zeros([NUM_STATES, 3], dtype=float)
for idx, example in tqdm(enumerate(x)):
    weights[idx] = example["weights"]
    data = example["data"]
    traj_states = np.zeros([150, 25], dtype=int)
    traj_rewards = np.zeros([150], dtype=float)
    for t in range(len(data)):
        traj_states[t] = data[t][0]
        traj_rewards[t] = data[t][1]
    states[idx] = traj_states
    rewards[idx] = traj_rewards

1010000it [02:05, 8047.23it/s]


In [6]:
states[0]

array([[2, 0, 3, ..., 3, 3, 3],
       [3, 0, 0, ..., 3, 3, 3],
       [2, 0, 3, ..., 3, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [23]:
rewards[5000]

array([10.18885403, 12.21433581,  3.15487071, 18.94940075,  3.19103176,
       18.11223085,  7.82594034,  1.78203997,  1.39175277, 10.11324955,
        0.71283505,  1.56211507,  7.76660506, 16.77078216,  0.68539243,
        7.06386532,  0.99316186,  1.9413464 , 17.84870964, 11.03568938,
        7.40704388,  1.77736511, 16.8160805 ,  1.41534585,  8.57632409,
       17.89465163, 17.29654965,  1.12928168,  1.12278827,  1.3619686 ,
       10.53958953,  2.25028661, 17.45309981,  1.22743015,  7.91057486,
        8.13050388,  1.4512821 ,  7.28642997,  7.84145863,  1.88668597,
       17.19425345,  1.55977764,  1.35559172,  1.40621269,  1.49159914,
        1.85285822,  2.15020718,  2.13575139, 11.20978881, 17.11746891,
        1.0897207 ,  1.13268161,  1.4619315 , 16.84054203,  0.97753116,
       10.08591934,  1.01709627,  1.91008913, 11.53382846, 18.29078858,
        8.02140783, 11.22201958, 17.13543704,  1.18458577,  0.80056305,
        7.12086731,  0.61393466,  1.38526349,  2.12510612, 12.12

In [22]:
weights[5000]

array([0.8167437 , 0.32796258, 0.4747318 ])

In [4]:
states_copy = np.copy(states)

In [6]:
perm = np.arange(4)
np.random.shuffle(perm)
perm

array([1, 3, 0, 2])

In [7]:
states_copy[1]

array([[3, 3, 3, ..., 3, 3, 2],
       [1, 3, 3, ..., 3, 1, 3],
       [1, 1, 3, ..., 3, 3, 1],
       ...,
       [3, 3, 3, ..., 3, 3, 1],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [8]:
perm[states_copy[1]]

array([[2, 2, 2, ..., 2, 2, 0],
       [3, 2, 2, ..., 2, 3, 2],
       [3, 3, 2, ..., 2, 2, 3],
       ...,
       [2, 2, 2, ..., 2, 2, 3],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [5]:
# np.save("states_460000.npy", states)

In [6]:
# np.save("rewards_460000.npy", rewards)

In [10]:
np.save("states_100000.npy", states)
np.save("rewards_100000.npy", rewards)

In [24]:
np.save(f"states_{NUM_STATES}.npy", states)
np.save(f"rewards_{NUM_STATES}.npy", rewards)
np.save(f"weights_{NUM_STATES}.npy", weights)

In [25]:
NUM_STATES_TEST = 10100

In [26]:
np.save(f"states_{NUM_STATES_TEST}.npy", states[:NUM_STATES_TEST])
np.save(f"rewards_{NUM_STATES_TEST}.npy", rewards[:NUM_STATES_TEST])
np.save(f"weights_{NUM_STATES_TEST}.npy", weights[:NUM_STATES_TEST])

In [7]:
np.save("states_4600.npy", states[:4600])

In [8]:
np.save("rewards_4600.npy", rewards[:4600])

In [9]:
np.save("states_46000.npy", states[:46000])

In [10]:
np.save("rewards_46000.npy", rewards[:46000])

In [4]:
np.save("states_60000.npy", states[:60000])

In [5]:
np.save("rewards_60000.npy", rewards[:60000])

In [12]:
states.shape

(460000, 150, 25)

In [15]:
states[:, :, 12]

array([[3, 3, 3, ..., 1, 3, 3],
       [3, 2, 1, ..., 3, 1, 3],
       [3, 1, 1, ..., 1, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 2, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])